export const prCities = [
    { name: "Abatia", code: 898 },
    { name: "Adrianopolis", code: 3894 },
    { name: "Agudos do Sul", code: 2322 },
    { name: "Almirante Tamandare", code: 2913 },
    { name: "Altamira do Parana", code: 1562 },
    { name: "Altania", code: 112 },
    { name: "Alto Parana", code: 9878 },
    { name: "Alto Piquiri", code: 2881 },
    { name: "Alvorada do Sul", code: 5826 },
    { name: "Amapora", code: 865 },
    { name: "Ampere", code: 464 },
    { name: "Anahy", code: 6233 },
    { name: "Andira", code: 2815 },
    { name: "Angulo", code: 98 },
    { name: "Antonina", code: 6495 },
    { name: "Antonio Olinto", code: 99 },
    { name: "Apucarana", code: 8248 },
    { name: "Arapongas", code: 7118 },
    { name: "Arapoti", code: 8355 },
    { name: "Arapua", code: 965 },
    { name: "Araruna", code: 9245 },
    { name: "Araucaria", code: 9337 },
    { name: "Ariranha do Ivai", code: 918 },
    { name: "Assai", code: 284 },
    { name: "Assis Chateaubriand", code: 945 },
    { name: "Astorga", code: 7612 },
    { name: "Atalaia", code: 462 },
    { name: "Balsa Nova", code: 5811 },
    { name: "Bandeirantes", code: 284 },
    { name: "Barbosa Ferraz", code: 4462 },
    { name: "Barra do Jacare", code: 8396 },
    { name: "Barracao", code: 3376 },
    { name: "Bela Vista da Caroba", code: 4842 },
    { name: "Bela Vista do Paraiso", code: 988 },
    { name: "Bituruna", code: 4886 },
    { name: "Boa Esperanca do Iguacu", code: 7833 },
    { name: "Boa Esperanca", code: 1738 },
    { name: "Boa Ventura de Sao Roque", code: 514 },
    { name: "Boa Vista da Aparecida", code: 3274 },
    { name: "Bocaiuva do Sul", code: 148 },
    { name: "Bom Jesus do Sul", code: 5649 },
    { name: "Bom Sucesso do Sul", code: 1221 },
    { name: "Bom Sucesso", code: 891 },
    { name: "Borrazopolis", code: 915 },
    { name: "Braganey", code: 233 },
    { name: "Brasilandia do Sul", code: 5558 },
    { name: "Cafeara", code: 689 },
    { name: "Cafelandia", code: 8675 },
    { name: "Cafezal do Sul", code: 659 },
    { name: "California", code: 8857 },
    { name: "Cambara", code: 367 },
    { name: "Cambe", code: 4227 },
    { name: "Cambira", code: 7317 },
    { name: "Campina Grande do Sul", code: 6213 },
    { name: "Campina da Lagoa", code: 332 },
    { name: "Campina do Simao", code: 853 },
    { name: "Campo Bonito", code: 875 },
    { name: "Campo Largo", code: 1316 },
    { name: "Campo Magro", code: 837 },
    { name: "Campo Mourao", code: 5988 },
    { name: "Campo do Tenente", code: 79 },
    { name: "Candido de Abreu", code: 4269 },
    { name: "Candoi", code: 8131 },
    { name: "Cantagalo", code: 3639 },
    { name: "Capanema", code: 7357 },
    { name: "Capitao Leonidas Marques", code: 7973 },
    { name: "Carambei", code: 232 },
    { name: "Carlopolis", code: 8817 },
    { name: "Cascavel", code: 9555 },
    { name: "Castro", code: 1554 },
    { name: "Catanduvas", code: 5189 },
    { name: "Centenario do Sul", code: 4436 },
    { name: "Cerro Azul", code: 7546 },
    { name: "Ceu Azul", code: 2752 },
    { name: "Chopinzinho", code: 6953 },
    { name: "Cianorte", code: 3926 },
    { name: "Cidade Gaucha", code: 924 },
    { name: "Clevelandia", code: 6521 },
    { name: "Colombo", code: 984 },
    { name: "Colorado", code: 4926 },
    { name: "Congonhinhas", code: 2682 },
    { name: "Conselheiro Mairinck", code: 4733 },
    { name: "Contenda", code: 4728 },
    { name: "Corbelia", code: 7993 },
    { name: "Cornelio Procopio", code: 9932 },
    { name: "Coronel Domingos Soares", code: 1157 },
    { name: "Coronel Vivida", code: 685 },
    { name: "Corumbatai do Sul", code: 384 },
    { name: "Cruz Machado", code: 2421 },
    { name: "Cruzeiro do Iguacu", code: 1259 },
    { name: "Cruzeiro do Oeste", code: 4912 },
    { name: "Cruzeiro do Sul", code: 759 },
    { name: "Cruzmaltina", code: 7224 },
    { name: "Curitiba", code: 7383 },
    { name: "Curiuva", code: 2643 },
    { name: "Diamante d'Oeste", code: 392 },
    { name: "Diamante do Norte", code: 9223 },
    { name: "Diamante do Sul", code: 6972 },
    { name: "Dois Vizinhos", code: 9916 },
    { name: "Douradina", code: 586 },
    { name: "Doutor Camargo", code: 9868 },
    { name: "Doutor Ulysses", code: 443 },
    { name: "Eneas Marques", code: 9917 },
    { name: "Engenheiro Beltrao", code: 5552 },
    { name: "Entre Rios do Oeste", code: 1177 },
    { name: "Esperanca Nova", code: 5811 },
    { name: "Espigao Alto do Iguacu", code: 3753 },
    { name: "Farol", code: 11 },
    { name: "Faxinal", code: 1363 },
    { name: "Fazenda Rio Grande", code: 9778 },
    { name: "Fenix", code: 68 },
    { name: "Fernandes Pinheiro", code: 888 },
    { name: "Figueira", code: 8 },
    { name: "Flor da Serra do Sul", code: 84 },
    { name: "Florai", code: 8535 },
    { name: "Floresta", code: 381 },
    { name: "Florestopolis", code: 8762 },
    { name: "Florida", code: 773 },
    { name: "Formosa do Oeste", code: 186 },
    { name: "Foz do Iguacu", code: 3744 },
    { name: "Foz do Jordao", code: 5797 },
    { name: "Francisco Alves", code: 2277 },
    { name: "Francisco Beltrao", code: 3716 },
    { name: "General Carneiro", code: 8843 },
    { name: "Godoy Moreira", code: 154 },
    { name: "Goioere", code: 4834 },
    { name: "Goioxim", code: 4843 },
    { name: "Grandes Rios", code: 935 },
    { name: "Guaira", code: 2 },
    { name: "Guairaca", code: 149 },
    { name: "Guamiranga", code: 433 },
    { name: "Guapirama", code: 75 },
    { name: "Guaporema", code: 951 },
    { name: "Guaraci", code: 1887 },
    { name: "Guaraniacu", code: 483 },
    { name: "Guarapuava", code: 1156 },
    { name: "Guaraquecaba", code: 7534 },
    { name: "Guaratuba", code: 213 },
    { name: "Honorio Serpa", code: 83 },
    { name: "Ibaiti", code: 9998 },
    { name: "Ibema", code: 343 },
    { name: "Ibipora", code: 8254 },
    { name: "Icaraima", code: 8287 },
    { name: "Iguaracu", code: 335 },
    { name: "Iguatu", code: 8875 },
    { name: "Imbau", code: 791 },
    { name: "Imbituva", code: 2628 },
    { name: "Inacio Martins", code: 4897 },
    { name: "Inaja", code: 1249 },
    { name: "Indianopolis", code: 565 },
    { name: "Ipiranga", code: 2762 },
    { name: "Ipora", code: 948 },
    { name: "Iracema do Oeste", code: 323 },
    { name: "Irati", code: 496 },
    { name: "Iretama", code: 2126 },
    { name: "Itaguaje", code: 628 },
    { name: "Itaipulandia", code: 9467 },
    { name: "Itambaraca", code: 3548 },
    { name: "Itambe", code: 1649 },
    { name: "Itapejara d'Oeste", code: 9868 },
    { name: "Itaperucu", code: 153 },
    { name: "Itauna do Sul", code: 498 },
    { name: "Ivai", code: 1544 },
    { name: "Ivaipora", code: 7832 },
    { name: "Ivate", code: 3346 },
    { name: "Ivatuba", code: 167 },
    { name: "Jaboti", code: 3124 },
    { name: "Jacarezinho", code: 3855 },
    { name: "Jaguapita", code: 6253 },
    { name: "Jaguariaiva", code: 965 },
    { name: "Jandaia do Sul", code: 7366 },
    { name: "Janiopolis", code: 217 },
    { name: "Japira", code: 5898 },
    { name: "Japura", code: 6133 },
    { name: "Jardim Alegre", code: 7545 },
    { name: "Jardim Olinda", code: 8455 },
    { name: "Jataizinho", code: 3622 },
    { name: "Jesuitas", code: 1959 },
    { name: "Joaquim Tavora", code: 7242 },
    { name: "Jundiai do Sul", code: 5966 },
    { name: "Juranda", code: 4767 },
    { name: "Jussara", code: 8453 },
    { name: "Kalore", code: 6684 },
    { name: "Lapa", code: 5691 },
    { name: "Laranjal", code: 484 },
    { name: "Laranjeiras do Sul", code: 973 },
    { name: "Leopolis", code: 2444 },
    { name: "Lidianopolis", code: 8337 },
    { name: "Lindoeste", code: 1623 },
    { name: "Loanda", code: 6788 },
    { name: "Lobato", code: 589 },
    { name: "Londrina", code: 5931 },
    { name: "Luiziana", code: 579 },
    { name: "Lunardelli", code: 4297 },
    { name: "Lupionopolis", code: 9871 },
    { name: "Mallet", code: 4493 },
    { name: "Mambore", code: 147 },
    { name: "Mandaguacu", code: 378 },
    { name: "Mandaguari", code: 6918 },
    { name: "Mandirituba", code: 37 },
    { name: "Manfrinopolis", code: 223 },
    { name: "Mangueirinha", code: 1926 },
    { name: "Manoel Ribas", code: 6795 },
    { name: "Marechal Candido Rondon", code: 185 },
    { name: "Maria Helena", code: 9935 },
    { name: "Marialva", code: 6946 },
    { name: "Marilandia do Sul", code: 4627 },
    { name: "Marilena", code: 9358 },
    { name: "Mariluz", code: 6985 },
    { name: "Maringa", code: 815 },
    { name: "Mariopolis", code: 295 },
    { name: "Maripa", code: 399 },
    { name: "Marmeleiro", code: 668 },
    { name: "Marquinho", code: 7941 },
    { name: "Marumbi", code: 962 },
    { name: "Matelandia", code: 8257 },
    { name: "Matinhos", code: 238 },
    { name: "Mato Rico", code: 3571 },
    { name: "Maua da Serra", code: 326 },
    { name: "Medianeira", code: 255 },
    { name: "Mercedes", code: 714 },
    { name: "Mirador", code: 915 },
    { name: "Miraselva", code: 6152 },
    { name: "Missal", code: 568 },
    { name: "Moreira Sales", code: 2654 },
    { name: "Morretes", code: 3567 },
    { name: "Munhoz de Melo", code: 517 },
    { name: "Nossa Senhora das Gracas", code: 7558 },
    { name: "Nova Alianca do Ivai", code: 6999 },
    { name: "Nova America da Colina", code: 434 },
    { name: "Nova Aurora", code: 4324 },
    { name: "Nova Cantu", code: 9356 },
    { name: "Nova Esperanca do Sudoeste", code: 4642 },
    { name: "Nova Esperanca", code: 3396 },
    { name: "Nova Fatima", code: 2152 },
    { name: "Nova Laranjeiras", code: 7656 },
    { name: "Nova Londrina", code: 6524 },
    { name: "Nova Olimpia", code: 6819 },
    { name: "Nova Prata do Iguacu", code: 48 },
    { name: "Nova Santa Barbara", code: 9814 },
    { name: "Nova Santa Rosa", code: 61 },
    { name: "Nova Tebas", code: 2398 },
    { name: "Novo Itacolomi", code: 9449 },
    { name: "Ortigueira", code: 4825 },
    { name: "Ourizona", code: 4474 },
    { name: "Ouro Verde do Oeste", code: 7339 },
    { name: "Paicandu", code: 7681 },
    { name: "Palmas", code: 4416 },
    { name: "Palmeira", code: 1831 },
    { name: "Palmital", code: 985 },
    { name: "Palotina", code: 7315 },
    { name: "Paraiso do Norte", code: 47 },
    { name: "Paranacity", code: 8394 },
    { name: "Paranagua", code: 825 },
    { name: "Paranapoema", code: 5618 },
    { name: "Paranavai", code: 3571 },
    { name: "Pato Bragado", code: 6212 },
    { name: "Pato Branco", code: 9867 },
    { name: "Paula Freitas", code: 6497 },
    { name: "Paulo Frontin", code: 2122 },
    { name: "Peabiru", code: 4747 },
    { name: "Perobal", code: 273 },
    { name: "Perola d'Oeste", code: 138 },
    { name: "Perola", code: 1873 },
    { name: "Pien", code: 8383 },
    { name: "Pinhais", code: 6161 },
    { name: "Pinhal de Sao Bento", code: 2789 },
    { name: "Pinhalao", code: 4614 },
    { name: "Pinhao", code: 945 },
    { name: "Pirai do Sul", code: 59 },
    { name: "Piraquara", code: 7992 },
    { name: "Pitanga", code: 4119 },
    { name: "Pitangueiras", code: 4172 },
    { name: "Planaltina do Parana", code: 3471 },
    { name: "Planalto", code: 936 },
    { name: "Ponta Grossa", code: 9179 },
    { name: "Pontal do Parana", code: 6699 },
    { name: "Porecatu", code: 3362 },
    { name: "Porto Amazonas", code: 1272 },
    { name: "Porto Barreiro", code: 8912 },
    { name: "Porto Rico", code: 548 },
    { name: "Porto Vitoria", code: 71 },
    { name: "Prado Ferreira", code: 9491 },
    { name: "Pranchita", code: 8551 },
    { name: "Presidente Castelo Branco", code: 1595 },
    { name: "Primeiro de Maio", code: 825 },
    { name: "Prudentopolis", code: 6627 },
    { name: "Quarto Centenario", code: 6489 },
    { name: "Quatigua", code: 7765 },
    { name: "Quatro Barras", code: 9264 },
    { name: "Quatro Pontes", code: 5721 },
    { name: "Quedas do Iguacu", code: 2225 },
    { name: "Querencia do Norte", code: 4288 },
    { name: "Quinta do Sol", code: 2294 },
    { name: "Quitandinha", code: 1511 },
    { name: "Ramilandia", code: 6859 },
    { name: "Rancho Alegre d'Oeste", code: 737 },
    { name: "Rancho Alegre", code: 8661 },
    { name: "Realeza", code: 7216 },
    { name: "Reboucas", code: 6699 },
    { name: "Renascenca", code: 9851 },
    { name: "Reserva do Iguacu", code: 4689 },
    { name: "Reserva", code: 4655 },
    { name: "Ribeirao Claro", code: 2828 },
    { name: "Ribeirao do Pinhal", code: 6495 },
    { name: "Rio Azul", code: 7943 },
    { name: "Rio Bom", code: 7547 },
    { name: "Rio Bonito do Iguacu", code: 246 },
    { name: "Rio Branco do Ivai", code: 2864 },
    { name: "Rio Branco do Sul", code: 8575 },
    { name: "Rio Negro", code: 793 },
    { name: "Rolandia", code: 3535 },
    { name: "Roncador", code: 3223 },
    { name: "Rondon", code: 5797 },
    { name: "Rosario do Ivai", code: 9792 },
    { name: "Sabaudia", code: 2492 },
    { name: "Salgado Filho", code: 2213 },
    { name: "Salto do Itarare", code: 2345 },
    { name: "Salto do Lontra", code: 731 },
    { name: "Santa Amelia", code: 4162 },
    { name: "Santa Cecilia do Pavao", code: 7128 },
    { name: "Santa Cruz de Monte Castelo", code: 8427 },
    { name: "Santa Fe", code: 8913 },
    { name: "Santa Helena", code: 976 },
    { name: "Santa Ines", code: 7831 },
    { name: "Santa Isabel do Ivai", code: 5665 },
    { name: "Santa Izabel do Oeste", code: 197 },
    { name: "Santa Lucia", code: 758 },
    { name: "Santa Maria do Oeste", code: 3969 },
    { name: "Santa Mariana", code: 1428 },
    { name: "Santa Monica", code: 7853 },
    { name: "Santa Tereza do Oeste", code: 7668 },
    { name: "Santa Terezinha de Itaipu", code: 565 },
    { name: "Santana do Itarare", code: 3215 },
    { name: "Santo Antonio da Platina", code: 45 },
    { name: "Santo Antonio do Caiua", code: 5631 },
    { name: "Santo Antonio do Paraiso", code: 8215 },
    { name: "Santo Antonio do Sudoeste", code: 628 },
    { name: "Santo Inacio", code: 299 },
    { name: "Sao Carlos do Ivai", code: 1577 },
    { name: "Sao Jeronimo da Serra", code: 6131 },
    { name: "Sao Joao do Caiua", code: 241 },
    { name: "Sao Joao do Ivai", code: 7364 },
    { name: "Sao Joao do Triunfo", code: 588 },
    { name: "Sao Joao", code: 5735 },
    { name: "Sao Jorge d'Oeste", code: 1699 },
    { name: "Sao Jorge do Ivai", code: 4232 },
    { name: "Sao Jorge do Patrocinio", code: 189 },
    { name: "Sao Jose da Boa Vista", code: 9739 },
    { name: "Sao Jose das Palmeiras", code: 1292 },
    { name: "Sao Jose dos Pinhais", code: 2669 },
    { name: "Sao Manoel do Parana", code: 1675 },
    { name: "Sao Mateus do Sul", code: 134 },
    { name: "Sao Miguel do Iguacu", code: 8511 },
    { name: "Sao Pedro do Iguacu", code: 5587 },
    { name: "Sao Pedro do Ivai", code: 7715 },
    { name: "Sao Pedro do Parana", code: 3392 },
    { name: "Sao Sebastiao da Amoreira", code: 671 },
    { name: "Sao Tome", code: 5196 },
    { name: "Sapopema", code: 7787 },
    { name: "Sarandi", code: 1943 },
    { name: "Saudade do Iguacu", code: 621 },
    { name: "Senges", code: 5977 },
    { name: "Serranopolis do Iguacu", code: 6775 },
    { name: "Sertaneja", code: 7674 },
    { name: "Sertanopolis", code: 565 },
    { name: "Siqueira Campos", code: 892 },
    { name: "Sulina", code: 563 },
    { name: "Tamarana", code: 6339 },
    { name: "Tamboara", code: 2117 },
    { name: "Tapejara", code: 5473 },
    { name: "Tapira", code: 8138 },
    { name: "Teixeira Soares", code: 5416 },
    { name: "Telemaco Borba", code: 8743 },
    { name: "Terra Boa", code: 9439 },
    { name: "Terra Rica", code: 5881 },
    { name: "Terra Roxa", code: 1999 },
    { name: "Tibagi", code: 5622 },
    { name: "Tijucas do Sul", code: 8113 },
    { name: "Toledo", code: 2485 },
    { name: "Tomazina", code: 1848 },
    { name: "Tres Barras do Parana", code: 4331 },
    { name: "Tunas do Parana", code: 836 },
    { name: "Tuneiras do Oeste", code: 663 },
    { name: "Tupassi", code: 6524 },
    { name: "Turvo", code: 6496 },
    { name: "Ubirata", code: 8437 },
    { name: "Umuarama", code: 6728 },
    { name: "Uniao da Vitoria", code: 9183 },
    { name: "Uniflor", code: 3144 },
    { name: "Urai", code: 354 },
    { name: "Ventania", code: 2838 },
    { name: "Vera Cruz do Oeste", code: 8862 },
    { name: "Vere", code: 6739 },
    { name: "Vila Alta", code: 195 },
    { name: "Virmond", code: 1761 },
    { name: "Vitorino", code: 5846 },
    { name: "Wenceslau Braz", code: 9254 },
    { name: "Xambre", code: 7885 }
]
