export const rjCities = [
    { name: "Angra dos Reis", code: 4432 },
    { name: "Aperibe", code: 1757 },
    { name: "Araruama", code: 215 },
    { name: "Areal", code: 9423 },
    { name: "Armacao de Buzios", code: 22 },
    { name: "Arraial do Cabo", code: 6915 },
    { name: "Barra Mansa", code: 8917 },
    { name: "Barra do Pirai", code: 9833 },
    { name: "Belford Roxo", code: 5566 },
    { name: "Bom Jardim", code: 3821 },
    { name: "Bom Jesus do Itabapoana", code: 6877 },
    { name: "Cabo Frio", code: 5523 },
    { name: "Cachoeiras de Macacu", code: 8487 },
    { name: "Cambuci", code: 5 },
    { name: "Campos dos Goytacazes", code: 5329 },
    { name: "Cantagalo", code: 5781 },
    { name: "Carapebus", code: 4723 },
    { name: "Cardoso Moreira", code: 4494 },
    { name: "Carmo", code: 5177 },
    { name: "Casimiro de Abreu", code: 1155 },
    { name: "Comendador Levy Gasparian", code: 48 },
    { name: "Conceicao de Macabu", code: 66 },
    { name: "Cordeiro", code: 79 },
    { name: "Duas Barras", code: 7921 },
    { name: "Duque de Caxias", code: 63 },
    { name: "Engenheiro Paulo de Frontin", code: 97 },
    { name: "Guapimirim", code: 1633 },
    { name: "Iguaba Grande", code: 6364 },
    { name: "Itaborai", code: 8321 },
    { name: "Itaguai", code: 7886 },
    { name: "Italva", code: 2193 },
    { name: "Itaocara", code: 14 },
    { name: "Itaperuna", code: 46 },
    { name: "Itatiaia", code: 4346 },
    { name: "Japeri", code: 4869 },
    { name: "Laje do Muriae", code: 7146 },
    { name: "Macae", code: 81 },
    { name: "Macuco", code: 5846 },
    { name: "Mage", code: 1848 },
    { name: "Mangaratiba", code: 7232 },
    { name: "Marica", code: 6557 },
    { name: "Mendes", code: 23 },
    { name: "Miguel Pereira", code: 9179 },
    { name: "Miracema", code: 92 },
    { name: "Natividade", code: 5747 },
    { name: "Nilopolis", code: 9563 },
    { name: "Niteroi", code: 8986 },
    { name: "Nova Friburgo", code: 323 },
    { name: "Nova Iguacu", code: 6291 },
    { name: "Paracambi", code: 8555 },
    { name: "Paraiba do Sul", code: 4383 },
    { name: "Parati", code: 9386 },
    { name: "Paty do Alferes", code: 1731 },
    { name: "Petropolis", code: 4512 },
    { name: "Pinheiral", code: 68 },
    { name: "Pirai", code: 89 },
    { name: "Porciuncula", code: 54 },
    { name: "Porto Real", code: 3749 },
    { name: "Quatis", code: 2538 },
    { name: "Queimados", code: 5578 },
    { name: "Quissama", code: 3967 },
    { name: "Resende", code: 7961 },
    { name: "Rio Bonito", code: 8429 },
    { name: "Rio Claro", code: 259 },
    { name: "Rio das Flores", code: 8373 },
    { name: "Rio das Ostras", code: 7894 },
    { name: "Rio de Janeiro", code: 4491 },
    { name: "Santa Maria Madalena", code: 5774 },
    { name: "Santo Antonio de Padua", code: 5216 },
    { name: "Sao Fidelis", code: 6453 },
    { name: "Sao Francisco de Itabapoana", code: 3857 },
    { name: "Sao Goncalo", code: 49 },
    { name: "Sao Joao da Barra", code: 6942 },
    { name: "Sao Joao de Meriti", code: 3683 },
    { name: "Sao Jose de Uba", code: 7515 },
    { name: "Sao Jose do Vale do Rio Preto", code: 4772 },
    { name: "Sao Pedro da Aldeia", code: 2929 },
    { name: "Sao Sebastiao do Alto", code: 4256 },
    { name: "Sapucaia", code: 1988 },
    { name: "Saquarema", code: 3678 },
    { name: "Seropedica", code: 78 },
    { name: "Silva Jardim", code: 3555 },
    { name: "Sumidouro", code: 4198 },
    { name: "Tangua", code: 57 },
    { name: "Teresopolis", code: 3517 },
    { name: "Trajano de Morais", code: 3579 },
    { name: "Tres Rios", code: 1197 },
    { name: "Valenca", code: 55 },
    { name: "Varre-Sai", code: 122 },
    { name: "Vassouras", code: 177 },
    { name: "Volta Redonda", code: 833 }
]
