export const rsCities = [
    { name: "Agua Santa", code: 2857 },
    { name: "Agudo", code: 8554 },
    { name: "Ajuricaba", code: 1712 },
    { name: "Alecrim", code: 268 },
    { name: "Alegrete", code: 7676 },
    { name: "Alegria", code: 5963 },
    { name: "Alpestre", code: 4994 },
    { name: "Alto Alegre", code: 749 },
    { name: "Alto Feliz", code: 5758 },
    { name: "Alvorada", code: 8918 },
    { name: "Amaral Ferrador", code: 2551 },
    { name: "Ametista do Sul", code: 9678 },
    { name: "Andre da Rocha", code: 5297 },
    { name: "Anta Gorda", code: 4195 },
    { name: "Antonio Prado", code: 9274 },
    { name: "Arambare", code: 3138 },
    { name: "Ararica", code: 1016 },
    { name: "Aratiba", code: 5939 },
    { name: "Arroio Grande", code: 8555 },
    { name: "Arroio do Meio", code: 9802 },
    { name: "Arroio do Sal", code: 7194 },
    { name: "Arroio do Tigre", code: 1467 },
    { name: "Arroio dos Ratos", code: 8838 },
    { name: "Arvorezinha", code: 528 },
    { name: "Augusto Pestana", code: 2677 },
    { name: "Aurea", code: 9754 },
    { name: "Bage", code: 4392 },
    { name: "Balneario Pinhal", code: 5030 },
    { name: "Barao de Cotegipe", code: 9093 },
    { name: "Barao do Triunfo", code: 4551 },
    { name: "Barao", code: 566 },
    { name: "Barra Funda", code: 5375 },
    { name: "Barra do Guarita", code: 1743 },
    { name: "Barra do Quarai", code: 8896 },
    { name: "Barra do Ribeiro", code: 8499 },
    { name: "Barra do Rio Azul", code: 4515 },
    { name: "Barracao", code: 9932 },
    { name: "Barros Cassal", code: 666 },
    { name: "Benjamin Constant do Sul", code: 7989 },
    { name: "Bento Goncalves", code: 1587 },
    { name: "Boa Vista das Missoes", code: 5680 },
    { name: "Boa Vista do Burica", code: 8760 },
    { name: "Boa Vista do Sul", code: 3421 },
    { name: "Bom Jesus", code: 5949 },
    { name: "Bom Principio", code: 5816 },
    { name: "Bom Progresso", code: 7778 },
    { name: "Bom Retiro do Sul", code: 8829 },
    { name: "Boqueirao do Leao", code: 9379 },
    { name: "Bossoroca", code: 9734 },
    { name: "Braga", code: 5751 },
    { name: "Brochier", code: 4607 },
    { name: "Butia", code: 7541 },
    { name: "Cacapava do Sul", code: 9478 },
    { name: "Cacequi", code: 8889 },
    { name: "Cachoeira do Sul", code: 8315 },
    { name: "Cachoeirinha", code: 3226 },
    { name: "Cacique Doble", code: 3826 },
    { name: "Caibate", code: 4610 },
    { name: "Caicara", code: 6242 },
    { name: "Camaqua", code: 4819 },
    { name: "Camargo", code: 9636 },
    { name: "Cambara do Sul", code: 9377 },
    { name: "Campestre da Serra", code: 9524 },
    { name: "Campina das Missoes", code: 4536 },
    { name: "Campinas do Sul", code: 8092 },
    { name: "Campo Bom", code: 542 },
    { name: "Campo Novo", code: 1540 },
    { name: "Campos Borges", code: 2486 },
    { name: "Candelaria", code: 2904 },
    { name: "Candido Godoi", code: 2252 },
    { name: "Candiota", code: 4929 },
    { name: "Canela", code: 3468 },
    { name: "Cangucu", code: 1553 },
    { name: "Canoas", code: 6084 },
    { name: "Capao da Canoa", code: 996 },
    { name: "Capao do Leao", code: 6779 },
    { name: "Capela de Santana", code: 4868 },
    { name: "Capitao", code: 6257 },
    { name: "Capivari do Sul", code: 4973 },
    { name: "Caraa", code: 3420 },
    { name: "Carazinho", code: 6750 },
    { name: "Carlos Barbosa", code: 5216 },
    { name: "Carlos Gomes", code: 2314 },
    { name: "Casca", code: 6893 },
    { name: "Caseiros", code: 6842 },
    { name: "Catuipe", code: 8191 },
    { name: "Caxias do Sul", code: 3494 },
    { name: "Centenario", code: 8540 },
    { name: "Cerrito", code: 3785 },
    { name: "Cerro Branco", code: 3058 },
    { name: "Cerro Grande do Sul", code: 8561 },
    { name: "Cerro Grande", code: 9174 },
    { name: "Cerro Largo", code: 2339 },
    { name: "Chapada", code: 1652 },
    { name: "Charqueadas", code: 4458 },
    { name: "Charrua", code: 5189 },
    { name: "Chiapeta", code: 3687 },
    { name: "Chui", code: 1267 },
    { name: "Chuvisca", code: 8269 },
    { name: "Cidreira", code: 1645 },
    { name: "Ciriaco", code: 2263 },
    { name: "Colinas", code: 8953 },
    { name: "Colorado", code: 8683 },
    { name: "Condor", code: 3160 },
    { name: "Constantina", code: 5840 },
    { name: "Coqueiros do Sul", code: 1243 },
    { name: "Coronel Barros", code: 5017 },
    { name: "Coronel Bicaco", code: 9631 },
    { name: "Cotipora", code: 7983 },
    { name: "Coxilha", code: 120 },
    { name: "Crissiumal", code: 4493 },
    { name: "Cristal do Sul", code: 1130 },
    { name: "Cristal", code: 2008 },
    { name: "Cruz Alta", code: 2541 },
    { name: "Cruzeiro do Sul", code: 19 },
    { name: "David Canabarro", code: 6135 },
    { name: "Derrubadas", code: 3781 },
    { name: "Dezesseis de Novembro", code: 7707 },
    { name: "Dilermano de Aguiar", code: 7723 },
    { name: "Dois Irmaos das Missoes", code: 3717 },
    { name: "Dois Irmaos", code: 3909 },
    { name: "Dois Lajeados", code: 4449 },
    { name: "Dom Feliciano", code: 3724 },
    { name: "Dom Pedrito", code: 7222 },
    { name: "Dom Pedro de Alcantara", code: 8285 },
    { name: "Dona Francisca", code: 877 },
    { name: "Doutor Mauricio Cardoso", code: 1297 },
    { name: "Doutor Ricardo", code: 4734 },
    { name: "Eldorado do Sul", code: 7940 },
    { name: "Encantado", code: 2066 },
    { name: "Encruzilhada do Sul", code: 7747 },
    { name: "Engenho Velho", code: 657 },
    { name: "Entre Rios do Sul", code: 3604 },
    { name: "Entre-Ijuis", code: 1945 },
    { name: "Erebango", code: 8563 },
    { name: "Erechim", code: 8409 },
    { name: "Ernestina", code: 5300 },
    { name: "Erval Grande", code: 3548 },
    { name: "Erval Seco", code: 5848 },
    { name: "Esmeralda", code: 8053 },
    { name: "Esperanca do Sul", code: 3928 },
    { name: "Espumoso", code: 5383 },
    { name: "Estacao", code: 4146 },
    { name: "Estancia Velha", code: 8413 },
    { name: "Esteio", code: 8382 },
    { name: "Estrela Velha", code: 2959 },
    { name: "Estrela", code: 5682 },
    { name: "Eugenio de Castro", code: 92 },
    { name: "Fagundes Varela", code: 1064 },
    { name: "Farroupilha", code: 5401 },
    { name: "Faxinal do Soturno", code: 4582 },
    { name: "Faxinalzinho", code: 4592 },
    { name: "Fazenda Vilanova", code: 8568 },
    { name: "Feliz", code: 5871 },
    { name: "Flores da Cunha", code: 8399 },
    { name: "Floriano Peixoto", code: 1311 },
    { name: "Fontoura Xavier", code: 1303 },
    { name: "Formigueiro", code: 1328 },
    { name: "Fortaleza dos Valos", code: 1786 },
    { name: "Frederico Westphalen", code: 5629 },
    { name: "Garibaldi", code: 379 },
    { name: "Garruchos", code: 9090 },
    { name: "Gaurama", code: 8142 },
    { name: "General Camara", code: 8942 },
    { name: "Gentil", code: 5492 },
    { name: "Getulio Vargas", code: 7260 },
    { name: "Girua", code: 8738 },
    { name: "Glorinha", code: 603 },
    { name: "Gramado Xavier", code: 4764 },
    { name: "Gramado dos Loureiros", code: 5266 },
    { name: "Gramado", code: 7930 },
    { name: "Gravatai", code: 9 },
    { name: "Guabiju", code: 4338 },
    { name: "Guaiba", code: 6824 },
    { name: "Guapore", code: 2171 },
    { name: "Guarani das Missoes", code: 9287 },
    { name: "Harmonia", code: 2730 },
    { name: "Herval", code: 5622 },
    { name: "Herveiras", code: 1235 },
    { name: "Horizontina", code: 9046 },
    { name: "Hulha Negra", code: 9166 },
    { name: "Humaita", code: 229 },
    { name: "Ibarama", code: 6867 },
    { name: "Ibiaca", code: 3832 },
    { name: "Ibiraiaras", code: 1478 },
    { name: "Ibirapuita", code: 9454 },
    { name: "Ibiruba", code: 4944 },
    { name: "Igrejinha", code: 5999 },
    { name: "Ijui", code: 6738 },
    { name: "Ilopolis", code: 1835 },
    { name: "Imbe", code: 4370 },
    { name: "Imigrante", code: 7951 },
    { name: "Independencia", code: 2768 },
    { name: "Inhacora", code: 9570 },
    { name: "Ipe", code: 7917 },
    { name: "Ipiranga do Sul", code: 9937 },
    { name: "Irai", code: 7050 },
    { name: "Itaara", code: 1344 },
    { name: "Itacurubi", code: 3903 },
    { name: "Itapuca", code: 7976 },
    { name: "Itaqui", code: 3274 },
    { name: "Itatiba do Sul", code: 183 },
    { name: "Ivora", code: 9131 },
    { name: "Ivoti", code: 4676 },
    { name: "Jaboticaba", code: 8352 },
    { name: "Jacutinga", code: 2916 },
    { name: "Jaguarao", code: 440 },
    { name: "Jaguari", code: 4734 },
    { name: "Jaquirana", code: 6178 },
    { name: "Jari", code: 9572 },
    { name: "Joia", code: 5911 },
    { name: "Julio de Castilhos", code: 3451 },
    { name: "Lagoa Vermelha", code: 8086 },
    { name: "Lagoa dos Tres Cantos", code: 2060 },
    { name: "Lagoao", code: 3618 },
    { name: "Lajeado do Bugre", code: 2335 },
    { name: "Lajeado", code: 175 },
    { name: "Lavras do Sul", code: 5209 },
    { name: "Liberato Salzano", code: 3452 },
    { name: "Lindolfo Collor", code: 6903 },
    { name: "Linha Nova", code: 9562 },
    { name: "Macambara", code: 5137 },
    { name: "Machadinho", code: 131 },
    { name: "Mampituba", code: 9462 },
    { name: "Manoel Viana", code: 8852 },
    { name: "Maquine", code: 10 },
    { name: "Marata", code: 9456 },
    { name: "Marau", code: 4251 },
    { name: "Marcelino Ramos", code: 1060 },
    { name: "Mariana Pimentel", code: 2880 },
    { name: "Mariano Moro", code: 854 },
    { name: "Marques de Souza", code: 5568 },
    { name: "Mata", code: 9573 },
    { name: "Mato Castelhano", code: 8490 },
    { name: "Mato Leitao", code: 8219 },
    { name: "Maximiliano de Almeida", code: 4592 },
    { name: "Minas do Leao", code: 8240 },
    { name: "Miraguai", code: 1728 },
    { name: "Montauri", code: 9800 },
    { name: "Monte Alegre dos Campos", code: 7630 },
    { name: "Monte Belo do Sul", code: 8154 },
    { name: "Montenegro", code: 5864 },
    { name: "Mormaco", code: 8866 },
    { name: "Morrinhos do Sul", code: 6577 },
    { name: "Morro Redondo", code: 5660 },
    { name: "Morro Reuter", code: 8606 },
    { name: "Mostardas", code: 3517 },
    { name: "Mucum", code: 764 },
    { name: "Muitos Capoes", code: 8242 },
    { name: "Muliterno", code: 4023 },
    { name: "Nao-Me-Toque", code: 6455 },
    { name: "Nicolau Vergueiro", code: 8461 },
    { name: "Nonoai", code: 593 },
    { name: "Nova Alvorada", code: 364 },
    { name: "Nova Araca", code: 8427 },
    { name: "Nova Bassano", code: 8695 },
    { name: "Nova Boa Vista", code: 7289 },
    { name: "Nova Brescia", code: 9394 },
    { name: "Nova Candelaria", code: 8840 },
    { name: "Nova Esperanca do Sul", code: 1349 },
    { name: "Nova Hartz", code: 7296 },
    { name: "Nova Padua", code: 2082 },
    { name: "Nova Palma", code: 4493 },
    { name: "Nova Petropolis", code: 6848 },
    { name: "Nova Prata", code: 6549 },
    { name: "Nova Ramada", code: 7423 },
    { name: "Nova Roma do Sul", code: 4159 },
    { name: "Nova Santa Rita", code: 5278 },
    { name: "Novo Barreiro", code: 2144 },
    { name: "Novo Cabrais", code: 5013 },
    { name: "Novo Hamburgo", code: 417 },
    { name: "Novo Machado", code: 9843 },
    { name: "Novo Tiradentes", code: 2834 },
    { name: "Osorio", code: 5586 },
    { name: "Paim Filho", code: 7805 },
    { name: "Palmares do Sul", code: 3340 },
    { name: "Palmeira das Missoes", code: 1152 },
    { name: "Palmitinho", code: 5162 },
    { name: "Panambi", code: 4968 },
    { name: "Pantano Grande", code: 584 },
    { name: "Parai", code: 8103 },
    { name: "Paraiso do Sul", code: 6375 },
    { name: "Pareci Novo", code: 5251 },
    { name: "Parobe", code: 3780 },
    { name: "Passa Sete", code: 3275 },
    { name: "Passo Fundo", code: 8035 },
    { name: "Passo do Sobrado", code: 205 },
    { name: "Paverama", code: 6969 },
    { name: "Pedro Osorio", code: 7189 },
    { name: "Pejucara", code: 992 },
    { name: "Pelotas", code: 8963 },
    { name: "Picada Cafe", code: 7943 },
    { name: "Pinhal Grande", code: 6192 },
    { name: "Pinhal", code: 9843 },
    { name: "Pinheirinho do Vale", code: 8965 },
    { name: "Pinheiro Machado", code: 4310 },
    { name: "Pirapo", code: 3937 },
    { name: "Piratini", code: 8942 },
    { name: "Planalto", code: 3454 },
    { name: "Poco das Antas", code: 2606 },
    { name: "Pontao", code: 4191 },
    { name: "Ponte Preta", code: 8416 },
    { name: "Portao", code: 4672 },
    { name: "Porto Alegre", code: 5180 },
    { name: "Porto Lucena", code: 7152 },
    { name: "Porto Maua", code: 5758 },
    { name: "Porto Vera Cruz", code: 1301 },
    { name: "Porto Xavier", code: 8291 },
    { name: "Pouso Novo", code: 6750 },
    { name: "Presidente Lucena", code: 3934 },
    { name: "Progresso", code: 8273 },
    { name: "Protasio Alves", code: 7038 },
    { name: "Putinga", code: 8954 },
    { name: "Quarai", code: 205 },
    { name: "Quevedos", code: 6442 },
    { name: "Quinze de Novembro", code: 4163 },
    { name: "Redentora", code: 8527 },
    { name: "Relvado", code: 6892 },
    { name: "Restinga Seca", code: 8410 },
    { name: "Rio Grande", code: 8643 },
    { name: "Rio Pardo", code: 9098 },
    { name: "Rio dos Indios", code: 4581 },
    { name: "Riozinho", code: 8902 },
    { name: "Roca Sales", code: 1727 },
    { name: "Rodeio Bonito", code: 2584 },
    { name: "Rolante", code: 2752 },
    { name: "Ronda Alta", code: 4089 },
    { name: "Rondinha", code: 576 },
    { name: "Roque Gonzales", code: 2036 },
    { name: "Rosario do Sul", code: 4135 },
    { name: "Sagrada Familia", code: 3931 },
    { name: "Saldanha Marinho", code: 6577 },
    { name: "Salto do Jacui", code: 719 },
    { name: "Salvador das Missoes", code: 8750 },
    { name: "Salvador do Sul", code: 1013 },
    { name: "Sananduva", code: 6683 },
    { name: "Santa Barbara do Sul", code: 1979 },
    { name: "Santa Clara do Sul", code: 6194 },
    { name: "Santa Cruz do Sul", code: 7386 },
    { name: "Santa Maria do Herval", code: 5590 },
    { name: "Santa Maria", code: 4239 },
    { name: "Santa Rosa", code: 2770 },
    { name: "Santa Tereza", code: 9705 },
    { name: "Santa Vitoria do Palmar", code: 4137 },
    { name: "Santana da Boa Vista", code: 4283 },
    { name: "Santana do Livramento", code: 4516 },
    { name: "Santiago", code: 8949 },
    { name: "Santo Angelo", code: 2771 },
    { name: "Santo Antonio da Patrulha", code: 6849 },
    { name: "Santo Antonio das Missoes", code: 5048 },
    { name: "Santo Antonio do Palma", code: 5057 },
    { name: "Santo Antonio do Planalto", code: 4998 },
    { name: "Santo Augusto", code: 3224 },
    { name: "Santo Cristo", code: 5316 },
    { name: "Santo Expedito do Sul", code: 6716 },
    { name: "Sao Borja", code: 2929 },
    { name: "Sao Domingos do Sul", code: 9472 },
    { name: "Sao Francisco de Assis", code: 6063 },
    { name: "Sao Francisco de Paula", code: 1938 },
    { name: "Sao Gabriel", code: 1053 },
    { name: "Sao Jeronimo", code: 4211 },
    { name: "Sao Joao da Urtiga", code: 4864 },
    { name: "Sao Joao do Polesine", code: 259 },
    { name: "Sao Jorge", code: 5932 },
    { name: "Sao Jose das Missoes", code: 8790 },
    { name: "Sao Jose do Herval", code: 4370 },
    { name: "Sao Jose do Hortencio", code: 9067 },
    { name: "Sao Jose do Inhacora", code: 963 },
    { name: "Sao Jose do Norte", code: 3797 },
    { name: "Sao Jose do Ouro", code: 1606 },
    { name: "Sao Jose dos Ausentes", code: 9192 },
    { name: "Sao Leopoldo", code: 6385 },
    { name: "Sao Lourenco do Sul", code: 5547 },
    { name: "Sao Luiz Gonzaga", code: 3984 },
    { name: "Sao Marcos", code: 8826 },
    { name: "Sao Martinho da Serra", code: 8439 },
    { name: "Sao Martinho", code: 4970 },
    { name: "Sao Miguel das Missoes", code: 9044 },
    { name: "Sao Nicolau", code: 7569 },
    { name: "Sao Paulo das Missoes", code: 7365 },
    { name: "Sao Pedro da Serra", code: 1781 },
    { name: "Sao Pedro do Butia", code: 873 },
    { name: "Sao Pedro do Sul", code: 4789 },
    { name: "Sao Sebastiao do Cai", code: 8575 },
    { name: "Sao Sepe", code: 8377 },
    { name: "Sao Valentim do Sul", code: 7612 },
    { name: "Sao Valentim", code: 2583 },
    { name: "Sao Valerio do Sul", code: 7089 },
    { name: "Sao Vendelino", code: 3539 },
    { name: "Sao Vicente do Sul", code: 5573 },
    { name: "Sapiranga", code: 9516 },
    { name: "Sapucaia do Sul", code: 6155 },
    { name: "Sarandi", code: 8646 },
    { name: "Seberi", code: 7565 },
    { name: "Sede Nova", code: 6203 },
    { name: "Segredo", code: 6472 },
    { name: "Selbach", code: 923 },
    { name: "Senador Salgado Filho", code: 8513 },
    { name: "Sentinela do Sul", code: 108 },
    { name: "Serafina Correa", code: 5414 },
    { name: "Serio", code: 4343 },
    { name: "Sertao Santana", code: 4887 },
    { name: "Sertao", code: 5852 },
    { name: "Sete de Setembro", code: 1988 },
    { name: "Severiano de Almeida", code: 1073 },
    { name: "Silveira Martins", code: 1846 },
    { name: "Sinimbu", code: 4528 },
    { name: "Sobradinho", code: 7644 },
    { name: "Soledade", code: 8897 },
    { name: "Tabai", code: 7849 },
    { name: "Tapejara", code: 6719 },
    { name: "Tapera", code: 6965 },
    { name: "Tapes", code: 5084 },
    { name: "Taquara", code: 8529 },
    { name: "Taquari", code: 7033 },
    { name: "Taquarucu do Sul" },
    { name: "Tavares", code: 6826 },
    { name: "Tenente Portela", code: 4205 },
    { name: "Terra de Areia", code: 6640 },
    { name: "Teutonia", code: 3157 },
    { name: "Tiradentes do Sul", code: 9950 },
    { name: "Toropi", code: 298 },
    { name: "Torres", code: 2233 },
    { name: "Tramandai", code: 3262 },
    { name: "Travesseiro", code: 6741 },
    { name: "Tres Arroios", code: 4840 },
    { name: "Tres Cachoeiras", code: 142 },
    { name: "Tres Coroas", code: 3647 },
    { name: "Tres Forquilhas", code: 5942 },
    { name: "Tres Palmeiras", code: 7543 },
    { name: "Tres Passos", code: 5856 },
    { name: "Tres de Maio", code: 8221 },
    { name: "Trindade do Sul", code: 5965 },
    { name: "Triunfo", code: 9944 },
    { name: "Tucunduva", code: 6819 },
    { name: "Tunas", code: 4479 },
    { name: "Tupanci do Sul", code: 907 },
    { name: "Tupancireta", code: 5306 },
    { name: "Tupandi", code: 8254 },
    { name: "Tuparendi", code: 3523 },
    { name: "Turucu", code: 2589 },
    { name: "Ubiretama", code: 9579 },
    { name: "Uniao da Serra", code: 4570 },
    { name: "Unistalda", code: 5380 },
    { name: "Uruguaiana", code: 7861 },
    { name: "Vacaria", code: 2681 },
    { name: "Vale Real", code: 8222 },
    { name: "Vale Verde", code: 8628 },
    { name: "Vale do Sol", code: 3261 },
    { name: "Vanini", code: 7435 },
    { name: "Venancio Aires", code: 8622 },
    { name: "Vera Cruz", code: 3240 },
    { name: "Veranopolis", code: 7892 },
    { name: "Vespasiano Correa", code: 7803 },
    { name: "Viadutos", code: 4847 },
    { name: "Viamao", code: 5205 },
    { name: "Vicente Dutra", code: 4390 },
    { name: "Victor Graeff", code: 9874 },
    { name: "Vila Flores", code: 7345 },
    { name: "Vila Langaro", code: 3875 },
    { name: "Vila Maria", code: 4157 },
    { name: "Vila Nova do Sul", code: 8289 },
    { name: "Vista Alegre do Prata", code: 8201 },
    { name: "Vista Alegre", code: 7312 },
    { name: "Vista Gaucha", code: 9063 },
    { name: "Vitoria das Missoes", code: 4619 },
    { name: "Xangri-la", code: 140 }

]
