export const scCities = [
    { name: "Abdon Batista", code: 2282 },
    { name: "Abelardo Luz", code: 1476 },
    { name: "Agrolandia", code: 2661 },
    { name: "Agronomica", code: 182 },
    { name: "Agua Doce", code: 9937 },
    { name: "Aguas Frias", code: 7399 },
    { name: "Aguas Mornas", code: 118 },
    { name: "Aguas de Chapeco", code: 3632 },
    { name: "Alfredo Wagner", code: 5367 },
    { name: "Alto Bela Vista", code: 3478 },
    { name: "Anchieta", code: 1342 },
    { name: "Angelina", code: 841 },
    { name: "Anita Garibaldi", code: 32 },
    { name: "Anitapolis", code: 7498 },
    { name: "Antonio Carlos", code: 9872 },
    { name: "Apiuna", code: 6933 },
    { name: "Arabuta", code: 3781 },
    { name: "Araquari", code: 498 },
    { name: "Ararangua", code: 724 },
    { name: "Armazem", code: 8678 },
    { name: "Arroio Trinta", code: 8585 },
    { name: "Arvoredo", code: 8181 },
    { name: "Ascurra", code: 686 },
    { name: "Atalanta", code: 5898 },
    { name: "Aurora", code: 7216 },
    { name: "Balneario Arroio do Silva", code: 998 },
    { name: "Balneario Barra do Sul", code: 37 },
    { name: "Balneario Camboriu", code: 592 },
    { name: "Balneario Gaivota", code: 923 },
    { name: "Bandeirante", code: 384 },
    { name: "Barra Bonita", code: 7188 },
    { name: "Barra Velha", code: 184 },
    { name: "Bela Vista do Toldo", code: 283 },
    { name: "Belmonte", code: 9813 },
    { name: "Benedito Novo", code: 8349 },
    { name: "Biguacu", code: 7446 },
    { name: "Blumenau", code: 9364 },
    { name: "Bocaina do Sul", code: 6946 },
    { name: "Bom Jardim da Serra", code: 6854 },
    { name: "Bom Jesus do Oeste", code: 986 },
    { name: "Bom Jesus", code: 6124 },
    { name: "Bom Retiro", code: 7198 },
    { name: "Bombinhas", code: 9181 },
    { name: "Botuvera", code: 5136 },
    { name: "Braco do Norte", code: 47 },
    { name: "Braco do Trombudo", code: 5268 },
    { name: "Brunopolis", code: 544 },
    { name: "Brusque", code: 5352 },
    { name: "Cacador", code: 9125 },
    { name: "Caibi", code: 7457 },
    { name: "Calmon", code: 2744 },
    { name: "Camboriu", code: 7227 },
    { name: "Campo Alegre", code: 888 },
    { name: "Campo Belo do Sul", code: 7126 },
    { name: "Campo Ere", code: 1183 },
    { name: "Campos Novos", code: 1652 },
    { name: "Canelinha", code: 658 },
    { name: "Canoinhas", code: 3236 },
    { name: "Capao Alto", code: 1528 },
    { name: "Capinzal", code: 3515 },
    { name: "Capivari de Baixo", code: 6382 },
    { name: "Catanduvas", code: 87 },
    { name: "Caxambu do Sul", code: 847 },
    { name: "Celso Ramos", code: 166 },
    { name: "Cerro Negro", code: 136 },
    { name: "Chapadao do Lageado", code: 927 },
    { name: "Chapeco", code: 517 },
    { name: "Cocal do Sul", code: 3845 },
    { name: "Concordia", code: 4279 },
    { name: "Cordilheira Alta", code: 952 },
    { name: "Coronel Freitas", code: 695 },
    { name: "Coronel Martins", code: 4339 },
    { name: "Correia Pinto", code: 9928 },
    { name: "Corupa", code: 1284 },
    { name: "Criciuma", code: 298 },
    { name: "Cunha Pora", code: 7786 },
    { name: "Cunhatai", code: 926 },
    { name: "Curitibanos", code: 7956 },
    { name: "Descanso", code: 8114 },
    { name: "Dionisio Cerqueira", code: 446 },
    { name: "Dona Emma", code: 465 },
    { name: "Doutor Pedrinho", code: 593 },
    { name: "Entre Rios", code: 3942 },
    { name: "Ermo", code: 2861 },
    { name: "Erval Velho", code: 735 },
    { name: "Faxinal dos Guedes", code: 432 },
    { name: "Flor do Sertao", code: 1552 },
    { name: "Florianopolis", code: 955 },
    { name: "Formosa do Sul", code: 8489 },
    { name: "Forquilhinha", code: 987 },
    { name: "Fraiburgo", code: 4558 },
    { name: "Frei Rogerio", code: 58 },
    { name: "Galvao", code: 9517 },
    { name: "Garopaba", code: 1734 },
    { name: "Garuva", code: 251 },
    { name: "Gaspar", code: 1172 },
    { name: "Governador Celso Ramos", code: 3623 },
    { name: "Grao Para", code: 4491 },
    { name: "Gravatal", code: 2298 },
    { name: "Guabiruba", code: 5939 },
    { name: "Guaraciaba", code: 244 },
    { name: "Guaramirim", code: 1657 },
    { name: "Guaruja do Sul", code: 426 },
    { name: "Guatambu", code: 22 },
    { name: "Herval d'Oeste", code: 219 },
    { name: "Ibiam", code: 188 },
    { name: "Ibicare", code: 4233 },
    { name: "Ibirama", code: 899 },
    { name: "Icara", code: 753 },
    { name: "Ilhota", code: 7573 },
    { name: "Imarui", code: 8414 },
    { name: "Imbituba", code: 9264 },
    { name: "Imbuia", code: 5753 },
    { name: "Indaial", code: 2618 },
    { name: "Iomere", code: 7393 },
    { name: "Ipira", code: 2468 },
    { name: "Ipora do Oeste", code: 7862 },
    { name: "Ipuacu", code: 2244 },
    { name: "Ipumirim", code: 9167 },
    { name: "Iraceminha", code: 5928 },
    { name: "Irani", code: 9226 },
    { name: "Irati", code: 1958 },
    { name: "Irineopolis", code: 2713 },
    { name: "Ita", code: 1258 },
    { name: "Itaiopolis", code: 3624 },
    { name: "Itajai", code: 992 },
    { name: "Itapema", code: 758 },
    { name: "Itapiranga", code: 8244 },
    { name: "Itapoa", code: 583 },
    { name: "Ituporanga", code: 6847 },
    { name: "Jabora", code: 5543 },
    { name: "Jacinto Machado", code: 7246 },
    { name: "Jaguaruna", code: 3645 },
    { name: "Jaragua do Sul", code: 365 },
    { name: "Jardinopolis", code: 747 },
    { name: "Joacaba", code: 7519 },
    { name: "Joinville", code: 1782 },
    { name: "Jose Boiteux", code: 255 },
    { name: "Jupia", code: 939 },
    { name: "Lacerdopolis", code: 6466 },
    { name: "Lages", code: 8 },
    { name: "Laguna", code: 3389 },
    { name: "Lajeado Grande", code: 557 },
    { name: "Laurentino", code: 7686 },
    { name: "Lauro Muller", code: 6333 },
    { name: "Lebon Regis", code: 8183 },
    { name: "Leoberto Leal", code: 7397 },
    { name: "Lindoia do Sul", code: 6545 },
    { name: "Lontras", code: 8431 },
    { name: "Luiz Alves", code: 9987 },
    { name: "Luzerna", code: 953 },
    { name: "Macieira", code: 8453 },
    { name: "Mafra", code: 5243 },
    { name: "Major Gercino", code: 9171 },
    { name: "Major Vieira", code: 5199 },
    { name: "Maracaja", code: 4682 },
    { name: "Maravilha", code: 3833 },
    { name: "Marema", code: 8664 },
    { name: "Massaranduba", code: 417 },
    { name: "Matos Costa", code: 4638 },
    { name: "Meleiro", code: 891 },
    { name: "Mirim Doce", code: 845 },
    { name: "Modelo", code: 8211 },
    { name: "Mondai", code: 6719 },
    { name: "Monte Carlo", code: 899 },
    { name: "Monte Castelo", code: 828 },
    { name: "Morro Grande", code: 5375 },
    { name: "Morro da Fumaca", code: 487 },
    { name: "Navegantes", code: 522 },
    { name: "Nova Erechim", code: 3522 },
    { name: "Nova Itaberaba", code: 7229 },
    { name: "Nova Trento", code: 6933 },
    { name: "Nova Veneza", code: 1679 },
    { name: "Novo Horizonte", code: 1498 },
    { name: "Orleans", code: 6713 },
    { name: "Otacilio Costa", code: 3162 },
    { name: "Ouro Verde", code: 2652 },
    { name: "Ouro", code: 471 },
    { name: "Paial", code: 973 },
    { name: "Painel", code: 318 },
    { name: "Palhoca", code: 426 },
    { name: "Palma Sola", code: 4615 },
    { name: "Palmeira", code: 2181 },
    { name: "Palmitos", code: 2515 },
    { name: "Papanduva", code: 2585 },
    { name: "Paraiso", code: 8431 },
    { name: "Passo de Torres", code: 932 },
    { name: "Passos Maia", code: 3173 },
    { name: "Paulo Lopes", code: 7596 },
    { name: "Pedras Grandes", code: 299 },
    { name: "Penha", code: 8259 },
    { name: "Peritiba", code: 8754 },
    { name: "Petrolandia", code: 6892 },
    { name: "Picarras", code: 961 },
    { name: "Pinhalzinho", code: 7652 },
    { name: "Pinheiro Preto", code: 9827 },
    { name: "Piratuba", code: 8948 },
    { name: "Planalto Alegre", code: 3756 },
    { name: "Pomerode", code: 739 },
    { name: "Ponte Alta do Norte", code: 849 },
    { name: "Ponte Alta", code: 638 },
    { name: "Ponte Serrada", code: 6248 },
    { name: "Porto Belo", code: 6715 },
    { name: "Porto Uniao", code: 3445 },
    { name: "Pouso Redondo", code: 626 },
    { name: "Praia Grande", code: 62 },
    { name: "Presidente Castelo Branco", code: 613 },
    { name: "Presidente Getulio", code: 4871 },
    { name: "Presidente Nereu", code: 7597 },
    { name: "Princesa", code: 437 },
    { name: "Quilombo", code: 7154 },
    { name: "Rancho Queimado", code: 5226 },
    { name: "Rio Fortuna", code: 5664 },
    { name: "Rio Negrinho", code: 3376 },
    { name: "Rio Rufino", code: 2179 },
    { name: "Rio d'Oeste", code: 6589 },
    { name: "Rio das Antas", code: 6758 },
    { name: "Rio do Campo", code: 978 },
    { name: "Rio do Sul", code: 8128 },
    { name: "Rio dos Cedros", code: 122 },
    { name: "Riqueza", code: 948 },
    { name: "Rodeio", code: 447 },
    { name: "Romelandia", code: 5198 },
    { name: "Salete", code: 8523 },
    { name: "Saltinho", code: 2168 },
    { name: "Salto Veloso", code: 3142 },
    { name: "Sangao", code: 3364 },
    { name: "Santa Cecilia", code: 3519 },
    { name: "Santa Helena", code: 8257 },
    { name: "Santa Rosa de Lima", code: 2484 },
    { name: "Santa Rosa do Sul", code: 733 },
    { name: "Santa Terezinha do Progresso", code: 723 },
    { name: "Santa Terezinha", code: 418 },
    { name: "Santiago do Sul", code: 5677 },
    { name: "Santo Amaro da Imperatriz", code: 2362 },
    { name: "Sao Bento do Sul", code: 333 },
    { name: "Sao Bernardino", code: 7725 },
    { name: "Sao Bonifacio", code: 773 },
    { name: "Sao Carlos", code: 274 },
    { name: "Sao Cristovao do Sul", code: 21 },
    { name: "Sao Domingos", code: 764 },
    { name: "Sao Francisco do Sul", code: 3121 },
    { name: "Sao Joao Batista", code: 919 },
    { name: "Sao Joao do Itaperiu", code: 384 },
    { name: "Sao Joao do Oeste", code: 4885 },
    { name: "Sao Joao do Sul", code: 3429 },
    { name: "Sao Joaquim", code: 647 },
    { name: "Sao Jose do Cedro", code: 359 },
    { name: "Sao Jose do Cerrito", code: 6454 },
    { name: "Sao Jose", code: 5427 },
    { name: "Sao Lourenco d'Oeste", code: 699 },
    { name: "Sao Ludgero", code: 718 },
    { name: "Sao Martinho", code: 637 },
    { name: "Sao Miguel d'Oeste", code: 6858 },
    { name: "Sao Miguel da Boa Vista", code: 381 },
    { name: "Sao Pedro de Alcantara", code: 238 },
    { name: "Saudades", code: 9485 },
    { name: "Schroeder", code: 153 },
    { name: "Seara", code: 559 },
    { name: "Serra Alta", code: 592 },
    { name: "Sideropolis", code: 7652 },
    { name: "Sombrio", code: 9424 },
    { name: "Sul Brasil", code: 6192 },
    { name: "Taio", code: 1293 },
    { name: "Tangara", code: 22 },
    { name: "Tigrinhos", code: 2565 },
    { name: "Tijucas", code: 4324 },
    { name: "Timbe do Sul", code: 326 },
    { name: "Timbo Grande", code: 553 },
    { name: "Timbo", code: 492 },
    { name: "Tres Barras", code: 428 },
    { name: "Treviso", code: 154 },
    { name: "Treze Tilias", code: 6658 },
    { name: "Treze de Maio", code: 9692 },
    { name: "Trombudo Central", code: 8139 },
    { name: "Tubarao", code: 242 },
    { name: "Tunapolis", code: 11 },
    { name: "Turvo", code: 265 },
    { name: "Uniao do Oeste", code: 6348 },
    { name: "Urubici", code: 3614 },
    { name: "Urupema", code: 79 },
    { name: "Urussanga", code: 9835 },
    { name: "Vargeao", code: 3988 },
    { name: "Vargem Bonita", code: 9427 },
    { name: "Vargem", code: 421 },
    { name: "Vidal Ramos", code: 2489 },
    { name: "Videira", code: 6327 },
    { name: "Vitor Meireles", code: 52 },
    { name: "Witmarsum", code: 5778 },
    { name: "Xanxere", code: 4586 },
    { name: "Xavantina", code: 3717 },
    { name: "Xaxim", code: 2927 },
    { name: "Zortea", code: 421 }
]
