export const spCities = [
    { name: "Adamantina", code: 8122 },
    { name: "Adolfo", code: 567 },
    { name: "Aguai", code: 66 },
    { name: "Aguas da Prata", code: 2743 },
    { name: "Aguas de Lindoia", code: 8976 },
    { name: "Aguas de Santa Barbara", code: 3169 },
    { name: "Aguas de Sao Pedro", code: 1811 },
    { name: "Agudos", code: 7 },
    { name: "Alambari", code: 5812 },
    { name: "Alfredo Marcondes", code: 7128 },
    { name: "Altair", code: 9 },
    { name: "Altinopolis", code: 9 },
    { name: "Alto Alegre", code: 6544 },
    { name: "Aluminio", code: 528 },
    { name: "Alvares Florence", code: 3177 },
    { name: "Alvares Machado", code: 9535 },
    { name: "Alvaro de Carvalho", code: 3398 },
    { name: "Alvinlandia", code: 16 },
    { name: "Americana", code: 19 },
    { name: "Americo Brasiliense", code: 1 },
    { name: "Americo de Campos", code: 7691 },
    { name: "Amparo", code: 2396 },
    { name: "Analandia", code: 3898 },
    { name: "Andradina", code: 6332 },
    { name: "Angatuba", code: 688 },
    { name: "Anhembi", code: 7741 },
    { name: "Anhumas", code: 4944 },
    { name: "Aparecida d'Oeste", code: 2914 },
    { name: "Aparecida", code: 1352 },
    { name: "Apiai", code: 9835 },
    { name: "Aracariguama", code: 9418 },
    { name: "Aracatuba", code: 228 },
    { name: "Aracoiaba da Serra", code: 1 },
    { name: "Aramina", code: 5 },
    { name: "Arandu", code: 8855 },
    { name: "Arapei", code: 395 },
    { name: "Araraquara", code: 7784 },
    { name: "Araras", code: 4 },
    { name: "Arco-Iris", code: 89 },
    { name: "Arealva", code: 5332 },
    { name: "Areias", code: 3868 },
    { name: "Areiopolis", code: 4321 },
    { name: "Ariranha", code: 5142 },
    { name: "Artur Nogueira", code: 9475 },
    { name: "Aruja", code: 9772 },
    { name: "Aspasia", code: 1773 },
    { name: "Assis", code: 16 },
    { name: "Atibaia", code: 9832 },
    { name: "Auriflama", code: 5495 },
    { name: "Avai", code: 2341 },
    { name: "Avanhandava", code: 5144 },
    { name: "Avare", code: 6174 },
    { name: "Bady Bassitt", code: 4715 },
    { name: "Balbinos", code: 5165 },
    { name: "Balsamo", code: 615 },
    { name: "Bananal", code: 3867 },
    { name: "Barao de Antonina", code: 1735 },
    { name: "Barbosa", code: 2842 },
    { name: "Bariri", code: 5215 },
    { name: "Barra Bonita", code: 6799 },
    { name: "Barra do Chapeu", code: 9161 },
    { name: "Barra do Turvo", code: 6681 },
    { name: "Barretos", code: 3574 },
    { name: "Barrinha", code: 1555 },
    { name: "Barueri", code: 4525 },
    { name: "Bastos", code: 7786 },
    { name: "Batatais", code: 43 },
    { name: "Bauru", code: 8 },
    { name: "Bebedouro", code: 2531 },
    { name: "Bento de Abreu", code: 2 },
    { name: "Bernardino de Campos", code: 5755 },
    { name: "Bertioga", code: 6442 },
    { name: "Bilac", code: 7843 },
    { name: "Birigui", code: 6841 },
    { name: "Biritiba-Mirim", code: 12 },
    { name: "Boa Esperanca do Sul", code: 4852 },
    { name: "Bocaina", code: 2274 },
    { name: "Bofete", code: 37 },
    { name: "Boituva", code: 9577 },
    { name: "Bom Jesus dos Perdoes", code: 8766 },
    { name: "Bom Sucesso de Itarare", code: 7515 },
    { name: "Bora", code: 3792 },
    { name: "Boraceia", code: 7552 },
    { name: "Borborema", code: 819 },
    { name: "Borebi", code: 4 },
    { name: "Botucatu", code: 1118 },
    { name: "Braganca Paulista", code: 4873 },
    { name: "Brauna", code: 2312 },
    { name: "Brejo Alegre", code: 6283 },
    { name: "Brodosqui", code: 113 },
    { name: "Brotas", code: 3245 },
    { name: "Buri", code: 9 },
    { name: "Buritama", code: 5 },
    { name: "Buritizal", code: 1 },
    { name: "Cabralia Paulista", code: 8 },
    { name: "Cabreuva", code: 9893 },
    { name: "Cacapava", code: 4367 },
    { name: "Cachoeira Paulista", code: 61 },
    { name: "Caconde", code: 7211 },
    { name: "Cafelandia", code: 7717 },
    { name: "Caiabu", code: 5 },
    { name: "Caieiras", code: 2564 },
    { name: "Caiua", code: 4 },
    { name: "Cajamar", code: 86 },
    { name: "Cajati", code: 3187 },
    { name: "Cajobi", code: 1716 },
    { name: "Cajuru", code: 3276 },
    { name: "Campina do Monte Alegre", code: 4914 },
    { name: "Campinas", code: 8 },
    { name: "Campo Limpo Paulista", code: 23 },
    { name: "Campos Novos Paulista", code: 5986 },
    { name: "Campos do Jordao", code: 7991 },
    { name: "Cananeia", code: 679 },
    { name: "Canas", code: 7741 },
    { name: "Candido Mota", code: 5795 },
    { name: "Candido Rodrigues", code: 6676 },
    { name: "Canitar", code: 34 },
    { name: "Capao Bonito", code: 1 },
    { name: "Capela do Alto", code: 1349 },
    { name: "Capivari", code: 2162 },
    { name: "Caraguatatuba", code: 7229 },
    { name: "Carapicuiba", code: 6923 },
    { name: "Cardoso", code: 6 },
    { name: "Casa Branca", code: 268 },
    { name: "Cassia dos Coqueiros", code: 5577 },
    { name: "Castilho", code: 282 },
    { name: "Catanduva", code: 987 },
    { name: "Catigua", code: 7767 },
    { name: "Cedral", code: 4 },
    { name: "Cerqueira Cesar", code: 1416 },
    { name: "Cerquilho", code: 94 },
    { name: "Cesario Lange", code: 7836 },
    { name: "Charqueada", code: 4 },
    { name: "Chavantes", code: 9992 },
    { name: "Clementina", code: 9671 },
    { name: "Colina", code: 2344 },
    { name: "Colombia", code: 1832 },
    { name: "Conchal", code: 74 },
    { name: "Conchas", code: 2 },
    { name: "Cordeiropolis", code: 1 },
    { name: "Coroados", code: 2625 },
    { name: "Coronel Macedo", code: 239 },
    { name: "Corumbatai", code: 33 },
    { name: "Cosmopolis", code: 9151 },
    { name: "Cosmorama", code: 1927 },
    { name: "Cotia", code: 6 },
    { name: "Cravinhos", code: 1 },
    { name: "Cristais Paulista", code: 8982 },
    { name: "Cruzalia", code: 7 },
    { name: "Cruzeiro", code: 1836 },
    { name: "Cubatao", code: 963 },
    { name: "Cunha", code: 9222 },
    { name: "Descalvado", code: 69 },
    { name: "Diadema", code: 6466 },
    { name: "Dirce Reis", code: 4376 },
    { name: "Divinolandia", code: 3176 },
    { name: "Dobrada", code: 191 },
    { name: "Dois Corregos", code: 9 },
    { name: "Dolcinopolis", code: 4141 },
    { name: "Dourado", code: 655 },
    { name: "Dracena", code: 8165 },
    { name: "Duartina", code: 8632 },
    { name: "Dumont", code: 4323 },
    { name: "Echapora", code: 8827 },
    { name: "Eldorado", code: 5976 },
    { name: "Elias Fausto", code: 95 },
    { name: "Elisiario", code: 5 },
    { name: "Embauba", code: 2799 },
    { name: "Embu", code: 3634 },
    { name: "Embu-Guacu", code: 4835 },
    { name: "Emilianopolis", code: 9978 },
    { name: "Engenheiro Coelho", code: 4576 },
    { name: "Espirito Santo do Pinhal", code: 7722 },
    { name: "Espirito Santo do Turvo", code: 2883 },
    { name: "Estiva Gerbi", code: 8336 },
    { name: "Estrela d'Oeste", code: 5892 },
    { name: "Estrela do Norte", code: 17 },
    { name: "Euclides da Cunha Paulista", code: 4545 },
    { name: "Fartura", code: 6932 },
    { name: "Fernando Prestes", code: 2555 },
    { name: "Fernandopolis", code: 9979 },
    { name: "Fernao", code: 4162 },
    { name: "Ferraz de Vasconcelos", code: 4285 },
    { name: "Flora Rica", code: 9 },
    { name: "Floreal", code: 6524 },
    { name: "Florida Paulista", code: 6343 },
    { name: "Florinia", code: 1992 },
    { name: "Franca", code: 5843 },
    { name: "Francisco Morato", code: 3818 },
    { name: "Franco da Rocha", code: 331 },
    { name: "Gabriel Monteiro", code: 2 },
    { name: "Galia", code: 5 },
    { name: "Garca", code: 727 },
    { name: "Gastao Vidigal", code: 5262 },
    { name: "Gaviao Peixoto", code: 982 },
    { name: "General Salgado", code: 9123 },
    { name: "Getulina", code: 9586 },
    { name: "Glicerio", code: 5699 },
    { name: "Guaicara", code: 3 },
    { name: "Guaimbe", code: 7843 },
    { name: "Guaira", code: 896 },
    { name: "Guapiacu", code: 6494 },
    { name: "Guapiara", code: 2822 },
    { name: "Guara", code: 7474 },
    { name: "Guaracai", code: 2655 },
    { name: "Guaraci", code: 5426 },
    { name: "Guarani d'Oeste", code: 1537 },
    { name: "Guaranta", code: 8191 },
    { name: "Guararapes", code: 6292 },
    { name: "Guararema", code: 9 },
    { name: "Guaratingueta", code: 783 },
    { name: "Guarei", code: 4226 },
    { name: "Guariba", code: 4344 },
    { name: "Guaruja", code: 2611 },
    { name: "Guarulhos", code: 8527 },
    { name: "Guatapara", code: 5182 },
    { name: "Guzolandia", code: 5558 },
    { name: "Herculandia", code: 255 },
    { name: "Holambra", code: 7125 },
    { name: "Hortolandia", code: 36 },
    { name: "Iacanga", code: 5723 },
    { name: "Iacri", code: 1382 },
    { name: "Iaras", code: 9129 },
    { name: "Ibate", code: 8845 },
    { name: "Ibira", code: 4462 },
    { name: "Ibirarema", code: 3661 },
    { name: "Ibitinga", code: 9225 },
    { name: "Ibiuna", code: 3751 },
    { name: "Icem", code: 3874 },
    { name: "Iepe", code: 4115 },
    { name: "Igaracu do Tiete", code: 6561 },
    { name: "Igarapava", code: 3583 },
    { name: "Igarata", code: 2972 },
    { name: "Iguape", code: 4125 },
    { name: "Ilha Comprida", code: 7134 },
    { name: "Ilha Solteira", code: 6618 },
    { name: "Ilhabela", code: 8467 },
    { name: "Indaiatuba", code: 4 },
    { name: "Indiana", code: 2197 },
    { name: "Indiapora", code: 7311 },
    { name: "Inubia Paulista", code: 5799 },
    { name: "Ipaucu", code: 5989 },
    { name: "Ipero", code: 7 },
    { name: "Ipeuna", code: 4811 },
    { name: "Ipigua", code: 999 },
    { name: "Iporanga", code: 9 },
    { name: "Ipua", code: 2588 },
    { name: "Iracemapolis", code: 2838 },
    { name: "Irapua", code: 5119 },
    { name: "Irapuru", code: 2689 },
    { name: "Itabera", code: 9954 },
    { name: "Itai", code: 6418 },
    { name: "Itajobi", code: 26 },
    { name: "Itaju", code: 4 },
    { name: "Itanhaem", code: 3374 },
    { name: "Itaoca", code: 5999 },
    { name: "Itapecerica da Serra", code: 7353 },
    { name: "Itapetininga", code: 8943 },
    { name: "Itapeva", code: 6117 },
    { name: "Itapevi", code: 8 },
    { name: "Itapira", code: 7723 },
    { name: "Itapirapua Paulista", code: 3132 },
    { name: "Itapolis", code: 1 },
    { name: "Itaporanga", code: 758 },
    { name: "Itapui", code: 9742 },
    { name: "Itapura", code: 2719 },
    { name: "Itaquaquecetuba", code: 4494 },
    { name: "Itarare", code: 4334 },
    { name: "Itariri", code: 4566 },
    { name: "Itatiba", code: 1493 },
    { name: "Itatinga", code: 1 },
    { name: "Itirapina", code: 4547 },
    { name: "Itirapua", code: 4366 },
    { name: "Itobi", code: 2927 },
    { name: "Itu", code: 8532 },
    { name: "Itupeva", code: 4248 },
    { name: "Ituverava", code: 4844 },
    { name: "Jaborandi", code: 578 },
    { name: "Jaboticabal", code: 2939 },
    { name: "Jacarei", code: 7112 },
    { name: "Jaci", code: 3241 },
    { name: "Jacupiranga", code: 6451 },
    { name: "Jaguariuna", code: 1771 },
    { name: "Jales", code: 9636 },
    { name: "Jambeiro", code: 7677 },
    { name: "Jandira", code: 9864 },
    { name: "Jardinopolis", code: 19 },
    { name: "Jarinu", code: 7 },
    { name: "Jau", code: 1261 },
    { name: "Jeriquara", code: 2425 },
    { name: "Joanopolis", code: 865 },
    { name: "Joao Ramalho", code: 9586 },
    { name: "Jose Bonifacio", code: 85 },
    { name: "Julio Mesquita", code: 5153 },
    { name: "Jumirim", code: 3769 },
    { name: "Jundiai", code: 3 },
    { name: "Junqueiropolis", code: 5147 },
    { name: "Juquia", code: 7336 },
    { name: "Juquitiba", code: 7957 },
    { name: "Lagoinha", code: 5 },
    { name: "Laranjal Paulista", code: 2861 },
    { name: "Lavinia", code: 2653 },
    { name: "Lavrinhas", code: 5456 },
    { name: "Leme", code: 2 },
    { name: "Lencois Paulista", code: 4377 },
    { name: "Limeira", code: 5723 },
    { name: "Lindoia", code: 7276 },
    { name: "Lins", code: 3611 },
    { name: "Lorena", code: 7 },
    { name: "Lourdes", code: 2893 },
    { name: "Louveira", code: 9367 },
    { name: "Lucelia", code: 4784 },
    { name: "Lucianopolis", code: 5399 },
    { name: "Luis Antonio", code: 7 },
    { name: "Luiziania", code: 94 },
    { name: "Lupercio", code: 8 },
    { name: "Lutecia", code: 39 },
    { name: "Macatuba", code: 5531 },
    { name: "Macaubal", code: 3111 },
    { name: "Macedonia", code: 1 },
    { name: "Magda", code: 62 },
    { name: "Mairinque", code: 1718 },
    { name: "Mairipora", code: 6576 },
    { name: "Manduri", code: 7771 },
    { name: "Maraba Paulista", code: 5 },
    { name: "Maracai", code: 89 },
    { name: "Marapoama", code: 1976 },
    { name: "Mariapolis", code: 2 },
    { name: "Marilia", code: 8459 },
    { name: "Marinopolis", code: 49 },
    { name: "Martinopolis", code: 4666 },
    { name: "Matao", code: 1281 },
    { name: "Maua", code: 2141 },
    { name: "Mendonca", code: 888 },
    { name: "Meridiano", code: 333 },
    { name: "Mesopolis", code: 3528 },
    { name: "Miguelopolis", code: 9464 },
    { name: "Mineiros do Tiete", code: 5837 },
    { name: "Mira Estrela", code: 1588 },
    { name: "Miracatu", code: 7776 },
    { name: "Mirandopolis", code: 1 },
    { name: "Mirante do Paranapanema", code: 123 },
    { name: "Mirassol", code: 3291 },
    { name: "Mirassolandia", code: 1724 },
    { name: "Mococa", code: 7921 },
    { name: "Mogi Guacu", code: 28 },
    { name: "Moji das Cruzes", code: 7322 },
    { name: "Moji-Mirim", code: 9823 },
    { name: "Mombuca", code: 918 },
    { name: "Moncoes", code: 8 },
    { name: "Mongagua", code: 2154 },
    { name: "Monte Alegre do Sul", code: 32 },
    { name: "Monte Alto", code: 5 },
    { name: "Monte Aprazivel", code: 2957 },
    { name: "Monte Azul Paulista", code: 3529 },
    { name: "Monte Castelo", code: 6985 },
    { name: "Monte Mor", code: 7281 },
    { name: "Monteiro Lobato", code: 6178 },
    { name: "Morro Agudo", code: 5652 },
    { name: "Morungaba", code: 47 },
    { name: "Motuca", code: 7 },
    { name: "Murutinga do Sul", code: 8827 },
    { name: "Nantes", code: 2179 },
    { name: "Narandiba", code: 858 },
    { name: "Natividade da Serra", code: 3796 },
    { name: "Nazare Paulista", code: 4792 },
    { name: "Neves Paulista", code: 9 },
    { name: "Nhandeara", code: 8 },
    { name: "Nipoa", code: 756 },
    { name: "Nova Alianca", code: 5987 },
    { name: "Nova Campina", code: 67 },
    { name: "Nova Canaa Paulista", code: 8188 },
    { name: "Nova Castilho", code: 2846 },
    { name: "Nova Europa", code: 2464 },
    { name: "Nova Granada", code: 2119 },
    { name: "Nova Guataporanga", code: 3 },
    { name: "Nova Independencia", code: 9712 },
    { name: "Nova Luzitania", code: 9284 },
    { name: "Nova Odessa", code: 1867 },
    { name: "Novais", code: 8561 },
    { name: "Novo Horizonte", code: 5688 },
    { name: "Nuporanga", code: 3268 },
    { name: "Ocaucu", code: 3679 },
    { name: "Oleo", code: 8394 },
    { name: "Olimpia", code: 7522 },
    { name: "Onda Verde", code: 535 },
    { name: "Oriente", code: 7534 },
    { name: "Orindiuva", code: 1735 },
    { name: "Orlandia", code: 9727 },
    { name: "Osasco", code: 9 },
    { name: "Oscar Bressane", code: 1557 },
    { name: "Osvaldo Cruz", code: 277 },
    { name: "Ourinhos", code: 346 },
    { name: "Ouro Verde", code: 3 },
    { name: "Ouroeste", code: 324 },
    { name: "Pacaembu", code: 88 },
    { name: "Palestina", code: 76 },
    { name: "Palmares Paulista", code: 326 },
    { name: "Palmeira d'Oeste", code: 8322 },
    { name: "Palmital", code: 7887 },
    { name: "Panorama", code: 5128 },
    { name: "Paraguacu Paulista", code: 8423 },
    { name: "Paraibuna", code: 7364 },
    { name: "Paraiso", code: 4 },
    { name: "Paranapanema", code: 8916 },
    { name: "Paranapua", code: 122 },
    { name: "Parapua", code: 83 },
    { name: "Pardinho", code: 199 },
    { name: "Pariquera-Acu", code: 5683 },
    { name: "Parisi", code: 7 },
    { name: "Patrocinio Paulista", code: 7743 },
    { name: "Pauliceia", code: 321 },
    { name: "Paulinia", code: 5481 },
    { name: "Paulistania", code: 8497 },
    { name: "Paulo de Faria", code: 812 },
    { name: "Pederneiras", code: 172 },
    { name: "Pedra Bela", code: 243 },
    { name: "Pedranopolis", code: 4467 },
    { name: "Pedregulho", code: 3775 },
    { name: "Pedreira", code: 3428 },
    { name: "Pedrinhas Paulista", code: 9813 },
    { name: "Pedro de Toledo", code: 3977 },
    { name: "Penapolis", code: 1538 },
    { name: "Pereira Barreto", code: 1784 },
    { name: "Pereiras", code: 5613 },
    { name: "Peruibe", code: 4551 },
    { name: "Piacatu", code: 1799 },
    { name: "Piedade", code: 776 },
    { name: "Pilar do Sul", code: 9392 },
    { name: "Pindamonhangaba", code: 4 },
    { name: "Pindorama", code: 4363 },
    { name: "Pinhalzinho", code: 290 },
    { name: "Piquerobi", code: 61 },
    { name: "Piquete", code: 2493 },
    { name: "Piracaia", code: 3366 },
    { name: "Piracicaba", code: 4686 },
    { name: "Piraju", code: 7644 },
    { name: "Pirajui", code: 833 },
    { name: "Pirangi", code: 722 },
    { name: "Pirapora do Bom Jesus", code: 1822 },
    { name: "Pirapozinho", code: 3454 },
    { name: "Pirassununga", code: 138 },
    { name: "Piratininga", code: 3656 },
    { name: "Pitangueiras", code: 3425 },
    { name: "Planalto", code: 6818 },
    { name: "Platina", code: 2889 },
    { name: "Poa", code: 5919 },
    { name: "Poloni", code: 5274 },
    { name: "Pompeia", code: 4 },
    { name: "Pongai", code: 8266 },
    { name: "Pontal", code: 9365 },
    { name: "Pontalinda", code: 7495 },
    { name: "Pontes Gestal", code: 4456 },
    { name: "Populina", code: 5289 },
    { name: "Porangaba", code: 2751 },
    { name: "Porto Feliz", code: 154 },
    { name: "Porto Ferreira", code: 1391 },
    { name: "Potim", code: 6945 },
    { name: "Potirendaba", code: 9214 },
    { name: "Pracinha", code: 2 },
    { name: "Pradopolis", code: 3513 },
    { name: "Praia Grande", code: 53 },
    { name: "Pratania", code: 62 },
    { name: "Presidente Alves", code: 6 },
    { name: "Presidente Bernardes", code: 2685 },
    { name: "Presidente Epitacio", code: 2759 },
    { name: "Presidente Prudente", code: 1863 },
    { name: "Presidente Venceslau", code: 4322 },
    { name: "Promissao", code: 9978 },
    { name: "Quadra", code: 9155 },
    { name: "Quata", code: 1159 },
    { name: "Queiroz", code: 5142 },
    { name: "Queluz", code: 6432 },
    { name: "Quintana", code: 785 },
    { name: "Rafard", code: 3164 },
    { name: "Rancharia", code: 8151 },
    { name: "Redencao da Serra", code: 5896 },
    { name: "Regente Feijo", code: 6491 },
    { name: "Reginopolis", code: 46 },
    { name: "Registro", code: 1872 },
    { name: "Restinga", code: 5 },
    { name: "Ribeira", code: 1122 },
    { name: "Ribeirao Bonito", code: 4375 },
    { name: "Ribeirao Branco", code: 4729 },
    { name: "Ribeirao Corrente", code: 3769 },
    { name: "Ribeirao Grande", code: 6 },
    { name: "Ribeirao Pires", code: 5563 },
    { name: "Ribeirao Preto", code: 53 },
    { name: "Ribeirao do Sul", code: 9255 },
    { name: "Ribeirao dos Indios", code: 5921 },
    { name: "Rifaina", code: 59 },
    { name: "Rincao", code: 13 },
    { name: "Rinopolis", code: 1992 },
    { name: "Rio Claro", code: 7947 },
    { name: "Rio Grande da Serra", code: 1435 },
    { name: "Rio das Pedras", code: 9 },
    { name: "Riolandia", code: 4734 },
    { name: "Riversul", code: 8 },
    { name: "Rosana", code: 5469 },
    { name: "Roseira", code: 6976 },
    { name: "Rubiacea", code: 1952 },
    { name: "Rubineia", code: 5336 },
    { name: "Sabino", code: 9184 },
    { name: "Sagres", code: 2018 },
    { name: "Sales Oliveira", code: 3836 },
    { name: "Sales", code: 4127 },
    { name: "Salesopolis", code: 44 },
    { name: "Salmourao", code: 25 },
    { name: "Saltinho", code: 8 },
    { name: "Salto Grande", code: 1178 },
    { name: "Salto de Pirapora", code: 84 },
    { name: "Salto", code: 5 },
    { name: "Sandovalina", code: 9681 },
    { name: "Santa Adelia", code: 1763 },
    { name: "Santa Albertina", code: 7287 },
    { name: "Santa Barbara d'Oeste", code: 2 },
    { name: "Santa Branca", code: 6171 },
    { name: "Santa Clara d'Oeste", code: 8527 },
    { name: "Santa Cruz da Conceicao", code: 9634 },
    { name: "Santa Cruz da Esperanca", code: 888 },
    { name: "Santa Cruz das Palmeiras", code: 5451 },
    { name: "Santa Cruz do Rio Pardo", code: 4571 },
    { name: "Santa Ernestina", code: 8264 },
    { name: "Santa Fe do Sul", code: 4995 },
    { name: "Santa Gertrudes", code: 5663 },
    { name: "Santa Isabel", code: 7 },
    { name: "Santa Lucia", code: 127 },
    { name: "Santa Maria da Serra", code: 4962 },
    { name: "Santa Mercedes", code: 3535 },
    { name: "Santa Rita d'Oeste", code: 1853 },
    { name: "Santa Rita do Passa Quatro", code: 11 },
    { name: "Santa Rosa de Viterbo", code: 5592 },
    { name: "Santa Salete", code: 5579 },
    { name: "Santana da Ponte Pensa", code: 48 },
    { name: "Santana de Parnaiba", code: 528 },
    { name: "Santo Anastacio", code: 3911 },
    { name: "Santo Andre", code: 3756 },
    { name: "Santo Antonio da Alegria", code: 6945 },
    { name: "Santo Antonio de Posse", code: 6668 },
    { name: "Santo Antonio do Aracangua", code: 7 },
    { name: "Santo Antonio do Jardim", code: 7245 },
    { name: "Santo Antonio do Pinhal", code: 87 },
    { name: "Santo Expedito", code: 3763 },
    { name: "Santopolis do Aguapei", code: 4446 },
    { name: "Santos", code: 6736 },
    { name: "Sao Bento do Sapucai", code: 3385 },
    { name: "Sao Bernardo do Campo", code: 9339 },
    { name: "Sao Caetano do Sul", code: 3655 },
    { name: "Sao Carlos", code: 6118 },
    { name: "Sao Francisco", code: 777 },
    { name: "Sao Joao da Boa Vista", code: 5285 },
    { name: "Sao Joao das Duas Pontes", code: 4767 },
    { name: "Sao Joao de Iracema", code: 683 },
    { name: "Sao Joao do Pau d'Alho", code: 73 },
    { name: "Sao Joaquim da Barra", code: 71 },
    { name: "Sao Jose da Bela Vista", code: 7653 },
    { name: "Sao Jose do Barreiro", code: 6865 },
    { name: "Sao Jose do Rio Pardo", code: 614 },
    { name: "Sao Jose do Rio Preto", code: 712 },
    { name: "Sao Jose dos Campos", code: 2817 },
    { name: "Sao Lourenco da Serra", code: 7959 },
    { name: "Sao Luis do Paraitinga", code: 8 },
    { name: "Sao Manuel", code: 9368 },
    { name: "Sao Miguel Arcanjo", code: 6274 },
    { name: "Sao Paulo", code: 4367 },
    { name: "Sao Pedro do Turvo", code: 2223 },
    { name: "Sao Pedro", code: 4728 },
    { name: "Sao Roque", code: 4327 },
    { name: "Sao Sebastiao da Grama", code: 4212 },
    { name: "Sao Sebastiao", code: 4549 },
    { name: "Sao Simao", code: 4448 },
    { name: "Sao Vicente", code: 12 },
    { name: "Sarapui", code: 432 },
    { name: "Sarutaia", code: 56 },
    { name: "Sebastianopolis do Sul", code: 9234 },
    { name: "Serra Azul", code: 9665 },
    { name: "Serra Negra", code: 2193 },
    { name: "Serrana", code: 5462 },
    { name: "Sertaozinho", code: 3 },
    { name: "Sete Barras", code: 7282 },
    { name: "Severinia", code: 1995 },
    { name: "Silveiras", code: 8223 },
    { name: "Socorro", code: 3247 },
    { name: "Sorocaba", code: 2283 },
    { name: "Sud Mennucci", code: 6887 },
    { name: "Sumare", code: 2753 },
    { name: "Suzanapolis", code: 6194 },
    { name: "Suzano", code: 4371 },
    { name: "Tabapua", code: 3428 },
    { name: "Tabatinga", code: 4224 },
    { name: "Taboao da Serra", code: 6245 },
    { name: "Taciba", code: 3519 },
    { name: "Taguai", code: 1 },
    { name: "Taiacu", code: 4717 },
    { name: "Taiuva", code: 3225 },
    { name: "Tambau", code: 233 },
    { name: "Tanabi", code: 3481 },
    { name: "Tapirai", code: 1433 },
    { name: "Tapiratiba", code: 9238 },
    { name: "Taquaral", code: 5677 },
    { name: "Taquaritinga", code: 1572 },
    { name: "Taquarituba", code: 3223 },
    { name: "Taquarivai", code: 3432 },
    { name: "Tarabai", code: 5831 },
    { name: "Taruma", code: 8146 },
    { name: "Tatui", code: 8 },
    { name: "Taubate", code: 4336 },
    { name: "Tejupa", code: 4772 },
    { name: "Teodoro Sampaio", code: 1537 },
    { name: "Terra Roxa", code: 636 },
    { name: "Tiete", code: 81 },
    { name: "Timburi", code: 9217 },
    { name: "Torre de Pedra", code: 9949 },
    { name: "Torrinha", code: 8658 },
    { name: "Trabiju", code: 253 },
    { name: "Tremembe", code: 4415 },
    { name: "Tres Fronteiras", code: 4534 },
    { name: "Tuiuti", code: 374 },
    { name: "Tupa", code: 9 },
    { name: "Tupi Paulista", code: 2814 },
    { name: "Turiuba", code: 8547 },
    { name: "Turmalina", code: 72 },
    { name: "Ubarana", code: 2442 },
    { name: "Ubatuba", code: 9743 },
    { name: "Ubirajara", code: 5443 },
    { name: "Uchoa", code: 9 },
    { name: "Uniao Paulista", code: 3284 },
    { name: "Urania", code: 63 },
    { name: "Uru", code: 33 },
    { name: "Urupes", code: 7898 },
    { name: "Valentim Gentil", code: 8262 },
    { name: "Valinhos", code: 1233 },
    { name: "Valparaiso", code: 5573 },
    { name: "Vargem Grande Paulista", code: 6119 },
    { name: "Vargem Grande do Sul", code: 1141 },
    { name: "Vargem", code: 8586 },
    { name: "Varzea Paulista", code: 3413 },
    { name: "Vera Cruz", code: 6652 },
    { name: "Vinhedo", code: 5564 },
    { name: "Viradouro", code: 1581 },
    { name: "Vista Alegre do Alto", code: 1 },
    { name: "Vitoria Brasil", code: 6164 },
    { name: "Votorantim", code: 5814 },
    { name: "Votuporanga", code: 2727 },
    { name: "Zacarias", code: 6714 }

]
