export const HomeStyle = require("./home.pcss")
export const addCSS = require("./add.pcss")
export const filtersCSS = require("./filters.pcss")
export const barCSS = require("./bar.pcss")
export const routerCSS = require("./router.pcss")
export const tabsCSS = require("./tabs.pcss")
