module.exports = ["react",
		  "react-dom",
		  "redux", 
		  "rxjs", 
		  "material-ui", 
		  "firebase", 
		  "faker",
		  "lodash", 
		  "react-redux", 
		  "recompose",
		  "react-redux-firebase", 
		  "connected-react-router", 
		  "react-router",
		  "react-helmet", 
		  "redux-observable", 
		  "redux-logger"
		 ];
