---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: acharh
  name: acharh-ing
spec:
  rules:
  - host: acharh.cescoferraro.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: acharh-svc
          servicePort: 4000
