export const states = [
    // Estados
    { name: "Acre", uf: "AC", code: 1 },
    { name: "Alagoas", uf: "AL", code: 2 },
    { name: "Amapá", uf: "AP", code: 3 },
    { name: "Amazonas", uf: "AM", code: 4 },
    { name: "Bahia", uf: "BA", code: 5 },
    { name: "Ceará", uf: "CE", code: 6 },
    { name: "Distrito Federal", uf: "DF", code: 7 },
    { name: "Espírito Santo", uf: "ES", code: 8 },
    { name: "Goiás", uf: "GO", code: 9 },
    { name: "Maranhão", uf: "MA", code: 10 },
    { name: "Mato Grosso", uf: "MT", code: 11 },
    { name: "Mato Grossodo Sul", uf: "MS", code: 12 },
    { name: "Minas Gerais", uf: "MG", code: 13 },
    { name: "Pará", uf: "PA", code: 14 },
    { name: "Paraíba", uf: "PB", code: 15 },
    { name: "Paraná", uf: "PR", code: 16 },
    { name: "Pernambuco", uf: "PE", code: 17 },
    { name: "Piauí", uf: "PI", code: 18 },
    { name: "Rio de Janeiro", uf: "RJ", code: 19 },
    { name: "Rio Grande do Norte", uf: "RN", code: 20 },
    { name: "Rio Grande  do Sul", uf: "RS", code: 21 },
    { name: "Rondônia", uf: "RO", code: 22 },
    { name: "Roraima", uf: "RR", code: 23 },
    { name: "Santa Catarina", uf: "SC", code: 24 },
    { name: "São Paulo", uf: "SP", code: 25 },
    { name: "Sergipe", uf: "SE", code: 26 },
    { name: "Tocantins", uf: "TO", code: 27 },
    // Região
    { name: "Região Sul", uf: "S", code: 28, region: true },
    { name: "Região Sudoeste", uf: "SO", code: 29, region: true },
    { name: "Região Centro Oeste", uf: "CO", code: 30, region: true },
    { name: "Nordeste", uf: "NE", code: 31, region: true },
    { name: "Região Norte", uf: "N", code: 32, region: true }
]
