export const shirinkedList: string;
export const fullList: string;
export const add: string;
export const test: string;
export const flex: string;
export const icons: string;
export const image: string;
export const paid: string;
export const body: string;
