export const flex: string;
export const container: string;
export const containerHidden: string;
export const uf: string;
export const keyword: string;
export const city: string;
export const hidden: string;
export const mymove: string;
export const cescomove: string;
