job=build:
    description: "Runs Webpack Production"
    use: dev
    artifact: dist/ 
    mounts: [source]
    interactive: true
    command:  npm run prod
    depends: [vars, clean]

image=production:
    image: cescoferraro/achars
    tags: ["{env.VERSION}"]
    dockerfile: internal/docker/Dockerfile
    depends: [vars,build]
    description: "Build the frontend-image"

job=preview:
    ports: ["4000:4000"]
    use: dev
    mounts: [source]
    interactive: true
    command: node production.js
    depends: [vars,build]
    env:
      - "NODE_ENV=production"
